package corba.instantanea;


/**
* corba/instantanea/InstantaneaD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public final class InstantaneaD implements org.omg.CORBA.portable.IDLEntity
{
  public corba.instantanea.EstadoRobotD estadorobs[] = null;

  public InstantaneaD ()
  {
  } // ctor

  public InstantaneaD (corba.instantanea.EstadoRobotD[] _estadorobs)
  {
    estadorobs = _estadorobs;
  } // ctor

} // class InstantaneaD
