package corba.instantanea;


/**
* corba/instantanea/PuntosRobotDHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

abstract public class PuntosRobotDHelper
{
  private static String  _id = "IDL:corba/instantanea/PuntosRobotD:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.instantanea.PuntosRobotD that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.instantanea.PuntosRobotD extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = corba.khepera.robot.PosicionDHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "centro",
            _tcOf_members0,
            null);
          _tcOf_members0 = corba.khepera.robot.PosicionDHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (9, _tcOf_members0 );
          _members0[1] = new org.omg.CORBA.StructMember (
            "sens",
            _tcOf_members0,
            null);
          _tcOf_members0 = corba.khepera.robot.PosicionDHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (9, _tcOf_members0 );
          _members0[2] = new org.omg.CORBA.StructMember (
            "finsens",
            _tcOf_members0,
            null);
          _tcOf_members0 = corba.khepera.robot.PosicionDHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_array_tc (8, _tcOf_members0 );
          _members0[3] = new org.omg.CORBA.StructMember (
            "inter",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (corba.instantanea.PuntosRobotDHelper.id (), "PuntosRobotD", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.instantanea.PuntosRobotD read (org.omg.CORBA.portable.InputStream istream)
  {
    corba.instantanea.PuntosRobotD value = new corba.instantanea.PuntosRobotD ();
    value.centro = corba.khepera.robot.PosicionDHelper.read (istream);
    value.sens = new corba.khepera.robot.PosicionD[9];
    for (int _o0 = 0;_o0 < (9); ++_o0)
    {
      value.sens[_o0] = corba.khepera.robot.PosicionDHelper.read (istream);
    }
    value.finsens = new corba.khepera.robot.PosicionD[9];
    for (int _o1 = 0;_o1 < (9); ++_o1)
    {
      value.finsens[_o1] = corba.khepera.robot.PosicionDHelper.read (istream);
    }
    value.inter = new corba.khepera.robot.PosicionD[8];
    for (int _o2 = 0;_o2 < (8); ++_o2)
    {
      value.inter[_o2] = corba.khepera.robot.PosicionDHelper.read (istream);
    }
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.instantanea.PuntosRobotD value)
  {
    corba.khepera.robot.PosicionDHelper.write (ostream, value.centro);
    if (value.sens.length != (9))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i0 = 0;_i0 < (9); ++_i0)
    {
      corba.khepera.robot.PosicionDHelper.write (ostream, value.sens[_i0]);
    }
    if (value.finsens.length != (9))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i1 = 0;_i1 < (9); ++_i1)
    {
      corba.khepera.robot.PosicionDHelper.write (ostream, value.finsens[_i1]);
    }
    if (value.inter.length != (8))
      throw new org.omg.CORBA.MARSHAL (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    for (int _i2 = 0;_i2 < (8); ++_i2)
    {
      corba.khepera.robot.PosicionDHelper.write (ostream, value.inter[_i2]);
    }
  }

}
