package corba.khepera.escenario;


/**
* corba/khepera/escenario/EscenarioDHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

abstract public class EscenarioDHelper
{
  private static String  _id = "IDL:corba/khepera/escenario/EscenarioD:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.khepera.escenario.EscenarioD that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.khepera.escenario.EscenarioD extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = corba.khepera.escenario.RectanguloDHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "recs",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[1] = new org.omg.CORBA.StructMember (
            "nrecs",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[2] = new org.omg.CORBA.StructMember (
            "color",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (corba.khepera.escenario.EscenarioDHelper.id (), "EscenarioD", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.khepera.escenario.EscenarioD read (org.omg.CORBA.portable.InputStream istream)
  {
    corba.khepera.escenario.EscenarioD value = new corba.khepera.escenario.EscenarioD ();
    int _len0 = istream.read_long ();
    value.recs = new corba.khepera.escenario.RectanguloD[_len0];
    for (int _o1 = 0;_o1 < value.recs.length; ++_o1)
      value.recs[_o1] = corba.khepera.escenario.RectanguloDHelper.read (istream);
    value.nrecs = istream.read_ulong ();
    value.color = istream.read_ulong ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.khepera.escenario.EscenarioD value)
  {
    ostream.write_long (value.recs.length);
    for (int _i0 = 0;_i0 < value.recs.length; ++_i0)
      corba.khepera.escenario.RectanguloDHelper.write (ostream, value.recs[_i0]);
    ostream.write_ulong (value.nrecs);
    ostream.write_ulong (value.color);
  }

}
