package corba.robot;


/**
* corba/robot/_RobotSeguidorIntStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public class _RobotSeguidorIntStub extends org.omg.CORBA.portable.ObjectImpl implements corba.robot.RobotSeguidorInt
{

  public void ObtenerEstado (corba.instantanea.EstadoRobotDHolder est)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ObtenerEstado", true);
                $in = _invoke ($out);
                est.value = corba.instantanea.EstadoRobotDHelper.read ($in);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ObtenerEstado (est        );
            } finally {
                _releaseReply ($in);
            }
  } // ObtenerEstado

  public void ModificarEscenario (corba.khepera.escenario.EscenarioD esc)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ModificarEscenario", true);
                corba.khepera.escenario.EscenarioDHelper.write ($out, esc);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ModificarEscenario (esc        );
            } finally {
                _releaseReply ($in);
            }
  } // ModificarEscenario


  // raises (CORBA::COMM_FAILURE);
  public void ModificarObjetivo (corba.khepera.robot.PosicionD NuevoObj)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ModificarObjetivo", true);
                corba.khepera.robot.PosicionDHelper.write ($out, NuevoObj);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ModificarObjetivo (NuevoObj        );
            } finally {
                _releaseReply ($in);
            }
  } // ModificarObjetivo

  public void ModificarPosicion (corba.khepera.robot.PosicionD npos)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ModificarPosicion", true);
                corba.khepera.robot.PosicionDHelper.write ($out, npos);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ModificarPosicion (npos        );
            } finally {
                _releaseReply ($in);
            }
  } // ModificarPosicion

  public void ModificarLider (int idLider)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ModificarLider", true);
                $out.write_ulong (idLider);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                ModificarLider (idLider        );
            } finally {
                _releaseReply ($in);
            }
  } // ModificarLider

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/robot/RobotSeguidorInt:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RobotSeguidorIntStub
