package corba.robot;


/**
* corba/robot/RobotSeguidorIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public class RobotSeguidorIntPOATie extends RobotSeguidorIntPOA
{

  // Constructors

  public RobotSeguidorIntPOATie ( corba.robot.RobotSeguidorIntOperations delegate ) {
      this._impl = delegate;
  }
  public RobotSeguidorIntPOATie ( corba.robot.RobotSeguidorIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public corba.robot.RobotSeguidorIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (corba.robot.RobotSeguidorIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void ObtenerEstado (corba.instantanea.EstadoRobotDHolder est)
  {
    _impl.ObtenerEstado(est);
  } // ObtenerEstado

  public void ModificarEscenario (corba.khepera.escenario.EscenarioD esc)
  {
    _impl.ModificarEscenario(esc);
  } // ModificarEscenario


  // raises (CORBA::COMM_FAILURE);
  public void ModificarObjetivo (corba.khepera.robot.PosicionD NuevoObj)
  {
    _impl.ModificarObjetivo(NuevoObj);
  } // ModificarObjetivo

  public void ModificarPosicion (corba.khepera.robot.PosicionD npos)
  {
    _impl.ModificarPosicion(npos);
  } // ModificarPosicion

  public void ModificarLider (int idLider)
  {
    _impl.ModificarLider(idLider);
  } // ModificarLider

  private corba.robot.RobotSeguidorIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class RobotSeguidorIntPOATie
