package corba.camara;


/**
* corba/camara/CamaraIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public abstract class CamaraIntPOA extends org.omg.PortableServer.Servant
 implements corba.camara.CamaraIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("SuscribirRobot", new java.lang.Integer (0));
    _methods.put ("SuscribirConsola", new java.lang.Integer (1));
    _methods.put ("BajaRobot", new java.lang.Integer (2));
    _methods.put ("BajaConsola", new java.lang.Integer (3));
    _methods.put ("ObtenerLista", new java.lang.Integer (4));
    _methods.put ("ObtenerIPYPortDifusion", new java.lang.Integer (5));
    _methods.put ("ObtenerInstantanea", new java.lang.Integer (6));
    _methods.put ("ModificarEscenario", new java.lang.Integer (7));
    _methods.put ("ObtenerEscenario", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/camara/CamaraInt/SuscribirRobot
       {
         String IORrob = in.read_string ();
         corba.camara.suscripcionD $result = null;
         $result = this.SuscribirRobot (IORrob);
         out = $rh.createReply();
         corba.camara.suscripcionDHelper.write (out, $result);
         break;
       }

       case 1:  // corba/camara/CamaraInt/SuscribirConsola
       {
         String IORcons = in.read_string ();
         corba.camara.suscripcionD $result = null;
         $result = this.SuscribirConsola (IORcons);
         out = $rh.createReply();
         corba.camara.suscripcionDHelper.write (out, $result);
         break;
       }

       case 2:  // corba/camara/CamaraInt/BajaRobot
       {
         String IORrob = in.read_string ();
         this.BajaRobot (IORrob);
         out = $rh.createReply();
         break;
       }

       case 3:  // corba/camara/CamaraInt/BajaConsola
       {
         String IORcons = in.read_string ();
         this.BajaConsola (IORcons);
         out = $rh.createReply();
         break;
       }

       case 4:  // corba/camara/CamaraInt/ObtenerLista
       {
         corba.camara.ListaSuscripcionD $result = null;
         $result = this.ObtenerLista ();
         out = $rh.createReply();
         corba.camara.ListaSuscripcionDHelper.write (out, $result);
         break;
       }

       case 5:  // corba/camara/CamaraInt/ObtenerIPYPortDifusion
       {
         corba.camara.IPYPortD $result = null;
         $result = this.ObtenerIPYPortDifusion ();
         out = $rh.createReply();
         corba.camara.IPYPortDHelper.write (out, $result);
         break;
       }

       case 6:  // corba/camara/CamaraInt/ObtenerInstantanea
       {
         corba.instantanea.InstantaneaD $result = null;
         $result = this.ObtenerInstantanea ();
         out = $rh.createReply();
         corba.instantanea.InstantaneaDHelper.write (out, $result);
         break;
       }

       case 7:  // corba/camara/CamaraInt/ModificarEscenario
       {
         corba.khepera.escenario.EscenarioD esc = corba.khepera.escenario.EscenarioDHelper.read (in);
         this.ModificarEscenario (esc);
         out = $rh.createReply();
         break;
       }

       case 8:  // corba/camara/CamaraInt/ObtenerEscenario
       {
         corba.khepera.escenario.EscenarioD $result = null;
         $result = this.ObtenerEscenario ();
         out = $rh.createReply();
         corba.khepera.escenario.EscenarioDHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/camara/CamaraInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CamaraInt _this() 
  {
    return CamaraIntHelper.narrow(
    super._this_object());
  }

  public CamaraInt _this(org.omg.CORBA.ORB orb) 
  {
    return CamaraIntHelper.narrow(
    super._this_object(orb));
  }


} // class CamaraIntPOA
