package corba.camara;


/**
* corba/camara/CamaraIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public class CamaraIntPOATie extends CamaraIntPOA
{

  // Constructors

  public CamaraIntPOATie ( corba.camara.CamaraIntOperations delegate ) {
      this._impl = delegate;
  }
  public CamaraIntPOATie ( corba.camara.CamaraIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public corba.camara.CamaraIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (corba.camara.CamaraIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public corba.camara.suscripcionD SuscribirRobot (String IORrob)
  {
    return _impl.SuscribirRobot(IORrob);
  } // SuscribirRobot

  public corba.camara.suscripcionD SuscribirConsola (String IORcons)
  {
    return _impl.SuscribirConsola(IORcons);
  } // SuscribirConsola

  public void BajaRobot (String IORrob)
  {
    _impl.BajaRobot(IORrob);
  } // BajaRobot

  public void BajaConsola (String IORcons)
  {
    _impl.BajaConsola(IORcons);
  } // BajaConsola

  public corba.camara.ListaSuscripcionD ObtenerLista ()
  {
    return _impl.ObtenerLista();
  } // ObtenerLista

  public corba.camara.IPYPortD ObtenerIPYPortDifusion ()
  {
    return _impl.ObtenerIPYPortDifusion();
  } // ObtenerIPYPortDifusion

  public corba.instantanea.InstantaneaD ObtenerInstantanea ()
  {
    return _impl.ObtenerInstantanea();
  } // ObtenerInstantanea

  public void ModificarEscenario (corba.khepera.escenario.EscenarioD esc)
  {
    _impl.ModificarEscenario(esc);
  } // ModificarEscenario

  public corba.khepera.escenario.EscenarioD ObtenerEscenario ()
  {
    return _impl.ObtenerEscenario();
  } // ObtenerEscenario

  private corba.camara.CamaraIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class CamaraIntPOATie
