package corba.camara;


/**
* corba/camara/IPYPortD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public final class IPYPortD implements org.omg.CORBA.portable.IDLEntity
{
  public String ip = null;
  public int port = (int)0;

  public IPYPortD ()
  {
  } // ctor

  public IPYPortD (String _ip, int _port)
  {
    ip = _ip;
    port = _port;
  } // ctor

} // class IPYPortD
