package corba.camara;

/**
* corba/camara/IPYPortDHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public final class IPYPortDHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.camara.IPYPortD value = null;

  public IPYPortDHolder ()
  {
  }

  public IPYPortDHolder (corba.camara.IPYPortD initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.camara.IPYPortDHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.camara.IPYPortDHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.camara.IPYPortDHelper.type ();
  }

}
