package corba.camara;


/**
* corba/camara/ListaSuscripcionDHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

abstract public class ListaSuscripcionDHelper
{
  private static String  _id = "IDL:corba/camara/ListaSuscripcionD:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.camara.ListaSuscripcionD that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.camara.ListaSuscripcionD extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [2];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "IORrobots",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "IORconsolas",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (corba.camara.ListaSuscripcionDHelper.id (), "ListaSuscripcionD", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.camara.ListaSuscripcionD read (org.omg.CORBA.portable.InputStream istream)
  {
    corba.camara.ListaSuscripcionD value = new corba.camara.ListaSuscripcionD ();
    int _len0 = istream.read_long ();
    value.IORrobots = new String[_len0];
    for (int _o1 = 0;_o1 < value.IORrobots.length; ++_o1)
      value.IORrobots[_o1] = istream.read_string ();
    int _len1 = istream.read_long ();
    value.IORconsolas = new String[_len1];
    for (int _o2 = 0;_o2 < value.IORconsolas.length; ++_o2)
      value.IORconsolas[_o2] = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.camara.ListaSuscripcionD value)
  {
    ostream.write_long (value.IORrobots.length);
    for (int _i0 = 0;_i0 < value.IORrobots.length; ++_i0)
      ostream.write_string (value.IORrobots[_i0]);
    ostream.write_long (value.IORconsolas.length);
    for (int _i1 = 0;_i1 < value.IORconsolas.length; ++_i1)
      ostream.write_string (value.IORconsolas[_i1]);
  }

}
