package corba.consola;


/**
* corba/consola/ConsolaIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

abstract public class ConsolaIntHelper
{
  private static String  _id = "IDL:corba/consola/ConsolaInt:1.0";

  public static void insert (org.omg.CORBA.Any a, corba.consola.ConsolaInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba.consola.ConsolaInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corba.consola.ConsolaIntHelper.id (), "ConsolaInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba.consola.ConsolaInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ConsolaIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba.consola.ConsolaInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corba.consola.ConsolaInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.consola.ConsolaInt)
      return (corba.consola.ConsolaInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba.consola._ConsolaIntStub stub = new corba.consola._ConsolaIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corba.consola.ConsolaInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba.consola.ConsolaInt)
      return (corba.consola.ConsolaInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba.consola._ConsolaIntStub stub = new corba.consola._ConsolaIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
