package corba.consola;


/**
* corba/consola/ConsolaIntPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public abstract class ConsolaIntPOA extends org.omg.PortableServer.Servant
 implements corba.consola.ConsolaIntOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("ModificarEscenario", new java.lang.Integer (0));
    _methods.put ("estoyviva", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // corba/consola/ConsolaInt/ModificarEscenario
       {
         corba.khepera.escenario.EscenarioD esc = corba.khepera.escenario.EscenarioDHelper.read (in);
         this.ModificarEscenario (esc);
         out = $rh.createReply();
         break;
       }

       case 1:  // corba/consola/ConsolaInt/estoyviva
       {
         boolean $result = false;
         $result = this.estoyviva ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:corba/consola/ConsolaInt:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ConsolaInt _this() 
  {
    return ConsolaIntHelper.narrow(
    super._this_object());
  }

  public ConsolaInt _this(org.omg.CORBA.ORB orb) 
  {
    return ConsolaIntHelper.narrow(
    super._this_object(orb));
  }


} // class ConsolaIntPOA
