package corba.consola;


/**
* corba/consola/ConsolaInt.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public interface ConsolaInt extends ConsolaIntOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ConsolaInt
