package corba.consola;


/**
* corba/consola/ConsolaIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public interface ConsolaIntOperations 
{
  void ModificarEscenario (corba.khepera.escenario.EscenarioD esc);
  boolean estoyviva ();
} // interface ConsolaIntOperations
