package corba.consola;


/**
* corba/consola/ConsolaIntPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public class ConsolaIntPOATie extends ConsolaIntPOA
{

  // Constructors

  public ConsolaIntPOATie ( corba.consola.ConsolaIntOperations delegate ) {
      this._impl = delegate;
  }
  public ConsolaIntPOATie ( corba.consola.ConsolaIntOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public corba.consola.ConsolaIntOperations _delegate() {
      return this._impl;
  }
  public void _delegate (corba.consola.ConsolaIntOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public void ModificarEscenario (corba.khepera.escenario.EscenarioD esc)
  {
    _impl.ModificarEscenario(esc);
  } // ModificarEscenario

  public boolean estoyviva ()
  {
    return _impl.estoyviva();
  } // estoyviva

  private corba.consola.ConsolaIntOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class ConsolaIntPOATie
