package corba.khepera.robot;


/**
* corba/khepera/robot/PosicionD.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/Gustavo/Documents/AgenciaRobots/prj-corba/robot.idl
* mi?rcoles 20 de noviembre de 2013 17H35' CET
*/

public final class PosicionD implements org.omg.CORBA.portable.IDLEntity
{
  public float x = (float)0;
  public float y = (float)0;

  public PosicionD ()
  {
  } // ctor

  public PosicionD (float _x, float _y)
  {
    x = _x;
    y = _y;
  } // ctor

} // class PosicionD
